#!/usr/bin/env python
"""Render docs/QUALITY_REPORT.md from the real run's JSON output.

The report is generated, never hand-written, so it cannot drift from the data
it describes. Run after `make validate`:

    PYTHONPATH=src ./.venv/bin/python scripts/render_quality_report.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from impact.config import load_settings  # noqa: E402
from impact.store import read_json  # noqa: E402

STATUS_ICON = {"pass": "PASS", "fail": "FAIL", "warn": "WARN", "skipped": "SKIP"}


def fmt(value: object, width: int = 110) -> str:
    if value is None:
        return "—"
    if isinstance(value, (dict, list)):
        text = json.dumps(value, sort_keys=True)
    else:
        text = str(value)
    text = " ".join(text.split())
    return text if len(text) <= width else text[: width - 1] + "…"


def main() -> int:
    settings = load_settings()
    quality = read_json(settings.path("derived", "_quality_report.json"), {}) or {}
    features = read_json(settings.path("derived", "_feature_summary.json"), {}) or {}
    graph = read_json(settings.path("derived", "_graph_coverage.json"), {}) or {}
    clone = read_json(settings.path("raw", "git_extract", "clone_info.json"), {}) or {}
    rate = read_json(settings.path("raw", "github", "_rate_limit_summary.json"), {}) or {}
    runs = read_json(settings.path("raw", "extraction_runs.json"), []) or []
    manifest = read_json(ROOT / "artifacts" / "run_manifest.json", {}) or {}

    if not quality:
        print("no quality report found; run `make validate` first", file=sys.stderr)
        return 1

    out: list[str] = []
    a = out.append

    a("# Quality Report\n")
    a("_Generated by `scripts/render_quality_report.py` from the real run. "
      "Do not edit by hand._\n")
    a(f"* **Status:** `{quality.get('status', 'unknown')}`")
    a(f"* **Generated:** {quality.get('generated_at')}")
    a(f"* **Source SHA:** `{clone.get('analyzed_head_sha')}`")
    window = quality.get("window") or {}
    a(f"* **Window:** {window.get('start')} → {window.get('end')} "
      f"({window.get('lookback_days')} complete UTC days)")
    a(f"* **Clone:** {clone.get('clone_strategy')}, "
      f"{clone.get('commit_count_available')} commits available, "
      f"linear history = {clone.get('linear_history')}\n")

    # -- gates
    a("## Quality gates\n")
    summary = quality.get("gate_summary") or {}
    a("| " + " | ".join(f"{k}: {v}" for k, v in sorted(summary.items())) + " |")
    a("|" + "---|" * max(len(summary), 1) + "\n")
    a("| Gate | Result | Detail |")
    a("|---|---|---|")
    for gate in quality.get("gates", []):
        a(f"| `{gate['gate']}` | **{STATUS_ICON.get(gate['status'], gate['status'])}** "
          f"| {fmt(gate.get('detail'))} |")
    a("")

    # -- invariants
    checks = quality.get("table_checks") or quality.get("checks") or []
    if checks:
        by_status: dict[str, int] = {}
        for check in checks:
            by_status[check["status"]] = by_status.get(check["status"], 0) + 1
        a("## Table invariants\n")
        a(f"{len(checks)} checks across all tables: "
          + ", ".join(f"**{v} {k}**" for k, v in sorted(by_status.items())) + "\n")
        failing = [c for c in checks if c["status"] == "fail"]
        if failing:
            a("| Table | Check | Offenders | Detail |")
            a("|---|---|---|---|")
            for check in failing[:40]:
                a(f"| `{check['table']}` | `{check['check']}` "
                  f"| {check.get('offending_count')} | {fmt(check.get('detail'), 70)} |")
        else:
            a("No failing invariant checks.")
        a("")

    # -- row counts
    counts = quality.get("row_counts") or {}
    if counts:
        a("## Row counts\n")
        a("| Table | Rows |")
        a("|---|---:|")
        for name, rows in sorted(counts.items()):
            a(f"| `{name}` | {rows:,} |")
        a("")

    # -- coverage
    a("## Coverage\n")
    py = graph.get("python") or {}
    ts = graph.get("typescript_javascript") or {}
    total = (py.get("import_statements") or 0) + (ts.get("import_statements") or 0)
    external = (
        (py.get("by_resolution") or {}).get("external", 0)
        + (ts.get("by_resolution") or {}).get("external", 0)
        + (ts.get("by_resolution") or {}).get("external_alias", 0)
    )
    internal = (py.get("resolved_internal") or 0) + (ts.get("resolved_internal") or 0)
    resolvable = max(total - external, 1)
    a("### Dependency graph\n")
    a(f"* Tracked files: **{graph.get('tracked_files'):,}** → "
      f"**{graph.get('graph_nodes'):,}** nodes, **{graph.get('internal_edges'):,}** edges")
    a(f"* Python: {py.get('import_statements', 0):,} import statements, "
      f"{py.get('resolved_internal', 0):,} internal")
    a(f"* TypeScript/JS: {ts.get('import_statements', 0):,} import statements, "
      f"{ts.get('resolved_internal', 0):,} internal")
    a(f"* **In-repo resolution rate: {internal / resolvable:.1%}** "
      f"({internal:,} of {resolvable:,} resolvable)")
    a(f"* Files with no import parser: **{graph.get('not_parsed_files'):,}** "
      f"({', '.join(graph.get('not_parsed_languages') or [])})")
    a(f"* Python parse errors: {graph.get('parse_errors')}")
    a(f"* tsconfig scopes: {graph.get('tsconfig_scopes')} "
      f"({graph.get('tsconfig_alias_patterns')} alias patterns)\n")

    for key, title in (
        ("change_shape", "Change shape"),
        ("blast_radius", "Blast radius"),
        ("episodes", "Episodes"),
        ("regression", "Regression candidates"),
        ("review_intervention", "Review interventions"),
        ("anomaly", "Anomalies"),
    ):
        block = features.get(key)
        if not block:
            continue
        a(f"### {title}\n")
        a("```json")
        a(json.dumps(block, indent=2, sort_keys=True))
        a("```\n")

    completeness = features.get("completeness_by_month") or []
    if completeness:
        a("### Extraction completeness by month\n")
        a("| Month | PRs | With merge commit | With files | With reviews | Ranking eligible |")
        a("|---|---:|---:|---:|---:|---:|")
        for row in completeness:
            a(f"| {row['month']} | {row['pull_requests']:,} "
              f"| {row['with_merge_commit']:,} | {row['with_files']:,} "
              f"| {row['with_reviews']:,} | {row['ranking_eligible']:,} |")
        a("")

    # -- audits
    a("## Manual audit samples\n")
    a("Samples are drawn deterministically (stable hash of the identifier, no "
      "RNG), so a reviewer's recorded verdicts stay attached to the same rows "
      "across runs.\n")
    a("| Queue | File | Rows | Verdicts recorded |")
    a("|---|---|---:|---:|")
    for name in (
        "audit_stratified_prs", "audit_regression_candidates",
        "audit_review_interventions",
    ):
        path = ROOT / "reports" / f"{name}.json"
        rows = read_json(path, []) or []
        recorded = sum(1 for r in rows if r.get("audit_verdict") is not None)
        a(f"| `{name}` | `reports/{name}.json` | {len(rows)} | {recorded} |")
    a("")

    # -- cost
    a("## API cost and runtime\n")
    if rate:
        a("| Metric | Value |")
        a("|---|---:|")
        for key in (
            "graphql_requests", "graphql_points_spent", "graphql_remaining",
            "rest_requests", "retries", "rate_limit_sleep_seconds",
        ):
            if key in rate:
                a(f"| `{key}` | {rate[key]:,} |" if isinstance(rate[key], (int, float))
                  else f"| `{key}` | {rate[key]} |")
        a("")
    if runs:
        a("| Stage | Status | Duration (s) |")
        a("|---|---|---:|")
        seen: set[str] = set()
        for run in reversed(runs):
            if run["stage"] in seen:
                continue
            seen.add(run["stage"])
            a(f"| `{run['stage']}` | {run['status']} | {run.get('duration_seconds', 0):,.1f} |")
        a("")

    # -- gaps
    gaps = quality.get("known_gaps") or manifest.get("known_gaps") or []
    a("## Known gaps\n")
    if gaps:
        for gap in gaps:
            a(f"* {fmt(gap, 240)}")
    else:
        a("None recorded.")
    a("")

    target = ROOT / "docs" / "QUALITY_REPORT.md"
    target.write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"wrote {target.relative_to(ROOT)} ({len(out)} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
